### ISSUE TITLE
How to configuration for check the overall CPU Quota in heat?

### ISSUE THREAD

**Issue by currenjin** [SUSE/ekcp#11]
Hi!<br>
I wanna check the overall cpu quota.
If the cpu quota is above a certain level, running bash script.

I attached my code.
What parameters should I put in?

```yml
heat_template_version: 2016-10-14
description: Test AutoScaling
parameters:
  image:
    type: string
    description: Image used for servers
    default: 9946f794-fbf6-45e8-ae53-3aa7c47b57b0
  key:
    type: string
    description: SSH key to connect to the servers
    default: key
  flavor:
    type: string
    description: flavor used by the web servers
    default: m1.default
  network:
    type: string
    description: Network used by the server
    default: aa602b33-05f0-455e-a064-a5aabdd3a26c
  subnet_id:
    type: string
    description: subnet on which the load balancer will be located
    default: fcea64c8-f04d-42bc-ac1d-ea51f04294be
  external_network_id:
    type: string
    description: Neutron external network
    default: 22b36518-2c43-4242-aa56-5bb0222c0810
  pool_id:
    type: string
    description: add server on pool of loadbalancer
    default: 03d84efa-02d1-4206-9a77-7c6472de529f
  aws_lb:
    type: string
    description: scale out on loadbalacer of aws
    default: LB-170074009.ap-northeast-2.elb.amazonaws.com
resources:
  asg:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      max_size: 3
      resource:
        type: lb_server.yaml
        properties:
          flavor: {get_param: flavor}
          image: {get_param: image}
          key_name: {get_param: key}
          network: {get_param: network}
          pool_id: {get_param: pool_id}
          subnet: {get_param: subnet_id}
          metadata: {"metering.server_group": {get_param: "OS::stack_id"}}
  web_server_scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 80
      scaling_adjustment: 1
  web_server_scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 80
      scaling_adjustment: -1
```
